version: '3'

services:
  opensearch:
    image:  ${OSS_IMAGE}
    hostname: opensearch
    container_name: opensearch
    networks: 
      - opensearch # used by OpenSearch Dashboard
    environment:
      - cluster.name=opensearch
      - bootstrap.memory_lock=true
      - discovery.type=single-node
      - path.repo=/tmp
      - network.publish_host=127.0.0.1
      - logger.org.opensearch=warn
      - "OPENSEARCH_JAVA_OPTS=-Xms1g -Xmx1g"
      - "OPENSEARCH_INITIAL_ADMIN_PASSWORD=myStrongPassword123@456"
      - "plugins.security.ssl.http.enabled=false"
      - ${OSS_ENV_VAR:-FOO=bar}
    command: ${OS_COMMAND}
    ulimits:
      nproc: 65536
      nofile:
        soft: 65536
        hard: 65536
      memlock:
        soft: -1
        hard: -1
    ports:
      - 9200:9200
networks:
  opensearch:
    driver: bridge
